### ISSUE TITLE
Filter out values -0.5 < x <0.5

### ISSUE THREAD

**Issue by jacksonsj** [jason-p-pickering/data-pack-importer#67] opened 2018-03-06 21:22 UTC
These appear in Disagg Tools as -0 or 0 and this issue is tripping up many Country Teams. Given that these are approved as they're seen in the Disagg Tool -- as zeros -- and our team has been instructed to drop all zero values, filter these out with zeros.

**Debate over whether to cut off at 0.4 or 0.49 or 0.45** - Excel visually rounds anything <0.5 and >-0.5 to 0. See below.

![image](https://user-images.githubusercontent.com/31488407/37059103-898cb4f2-215a-11e8-9688-027ae5ca7bf2.png)

**Comment by jason-p-pickering** [comment] 2018-03-07 08:05
Duplicate of #70

**Closed by jason-p-pickering** 2018-03-07 08:05 UTC
